services:
  db:
    image: postgres:15
    container_name: siph_db
    restart: always
    environment:
      POSTGRES_DB: siph
      POSTGRES_USER: siph
      POSTGRES_PASSWORD: siph
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: siph_api
    restart: always

    env_file:
      - .env

    environment:
      DATABASE_URL: postgresql+psycopg2://siph:siph@db:5432/siph
      JWT_SECRET_KEY: change-me
      JWT_ALGORITHM: HS256
      JWT_EXPIRATION_MINUTES: 60
      GOOGLE_CLIENT_ID: 1026227617402-hts4hu699cuo0gmh5fg8sh8ncjfdvo76.apps.googleusercontent.com

      # Azure / Entra ID
      AZURE_TENANT_ID: 8091eb44-4181-4c3c-b53d-fd6add70b0d9
      AZURE_SPA_CLIENT_ID: 628629c9-2b9b-43e7-a9e4-949b5af8a5f4
      AZURE_API_CLIENT_ID: b6a729ea-ecc2-4014-814c-4c10d21a0e24
      AZURE_AUTHORITY: https://login.microsoftonline.com/8091eb44-4181-4c3c-b53d-fd6add70b0d9
      AZURE_API_SCOPE: api://b6a729ea-ecc2-4014-814c-4c10d21a0e24/access_as_user

      # CORS
      CORS_ORIGINS: http://localhost:4200,http://127.0.0.1:4200

    ports:
      - "8000:8000"

    depends_on:
      - db

    volumes:
      - .:/app
      - ./uploads:/app/uploads

    working_dir: /app

    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

volumes:
  pgdata:
